name: AsyncAPI documents processing

on:
  push:
    branches: [ master ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    #"standard step" where repo needs to be checked-out first
    - name: Checkout repo
      uses: actions/checkout@v2
      
    #Using another action for AsyncAPI for validation
    - name: Validating AsyncAPI document
      uses: WaleedAshraf/asyncapi-github-action@v0.0.6
      with:
        filepath: asyncapi.yaml
        
    # Get next version
    - name: Bump release version
      id: bump_version
      uses: christian-draeger/increment-semantic-version@1.0.2
      with:
        current-version: ${{ secrets.VERSION || 1.0.0 }}
        version-fragment: 'feature'

    - name: Do something with your bumped release version
      run: echo ${{ steps.bump_version.outputs.next-version }}
      # will print 2.12.0

    # Generate the HTML for github pages
    - name: Generating HTML from my AsyncAPI document
      uses: docker://asyncapi/github-action-for-generator:2.0.3
      with:
        template: '@asyncapi/html-template@0.24.9'  #In case of template from npm, because of @ it must be in quotes
        filepath: /home/runner/work/al-api-docs/al-api-docs/asyncapi.yaml
        parameters: version=${{ steps.bump_version.outputs.next-version }}
        output: docs
    
    #Update the VERSION github secret
    - name: Update VERSION
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'VERSION'
        value: ${{ steps.bump_version.outputs.next-version }}
        repository: ${{ github.repository }}
        token: ${{ secrets.GITHUB_TOKEN }}

    #Deploy to GH Pages
    - name: Deploy GH page
      uses: JamesIves/github-pages-deploy-action@3.4.2
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs