name: AsyncAPI documents processing

on:
  push:
    branches: [ master ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    #"standard step" where repo needs to be checked-out first
    - name: Checkout repo
      uses: actions/checkout@v2
      
    #Using another action for AsyncAPI for validation
    - name: Validating AsyncAPI document
      uses: WaleedAshraf/asyncapi-github-action@v0.0.6
      with:
        filepath: asyncapi.yaml

    - name: Tag and prepare release
      id: tag_and_prepare_release
      uses: K-Phoen/semver-release-action@master
      with:
        release_branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload release notes
      if: steps.tag_and_prepare_release.outputs.tag
      uses: Roang-zero1/github-create-release-action@master
      with:
        created_tag: ${{ steps.tag_and_prepare_release.outputs.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    # Generate the HTML for github pages
    - name: Generating HTML from my AsyncAPI document
      uses: docker://asyncapi/github-action-for-generator:2.0.3
      with:
        template: '@asyncapi/html-template@0.24.9'  #In case of template from npm, because of @ it must be in quotes
        filepath: /home/runner/work/al-api-docs/al-api-docs/asyncapi.yaml
        parameters: version=${{ steps.tag_and_prepare_release.outputs.tag  }}
        output: docs
    
    #Deploy to GH Pages
    - name: Deploy GH page
      uses: JamesIves/github-pages-deploy-action@3.4.2
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs